services:
  rabbitmq:
    image: rabbitmq:4.3.6-management
    container_name: command-flow-rabbitmq
    ports: ['5672:5672', '15672:15672']
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  postgres:
    image: postgres:18
    container_name: command-flow-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: command_flow
    volumes:
      - postgres_data:/var/liv/postgresql/data

volumes:
  postgres_data:
